### ISSUE TITLE
ViewCollection as an Array?

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-template-coffee#15]
Salut,

Actuellement les views de ViewsCollections sont dans un objet et c'est pas super pratique quand on a besoin de parcourir cette list... Il pourrait etre pas mal de le passer en Array, ce qui semble suivre un peu plus la logique des collections de backbones et qui facilite grandement sont utilisation par l'ajout de methodes bien pratiques.

**Comment by jsilvestre** [comment]
Bonjour,

C'est un objet pour des raisons de performances, @m4dz t'expliquera mieux que moi. Tu peux parcourir facilement un objet grâce à la librairie underscore, sur laquelle sont basées les "méthodes bien pratiques des collections Backbone". Par exemple http://underscorejs.org/#find, http://underscorejs.org/#where ou http://underscorejs.org/#findwhere.

**Comment by clochix** [comment]
Hello,
Quel est le statut de cette demande ? Est-elle toujours pertinente ?

**Comment by m4dz** [comment]
> Quel est le statut de cette demande

La réponse de @jsilvestre est parfaite : parcourir un objet à l'aide des méthodes underscore/lodash ou utiliser `Object.keys` est suffisant je dirai. Si on a vraiment besoin de plus, une lib comme [BabySitter](https://github.com/marionettejs/backbone.babysitter) est probalement la meilleure réponse.

La question se pose plus de la pertinence de maintenance de ce template si on choisit effectivement de basculer les apps standard vers Marionette (ce qui semble être le choix avec Contacts et Cozy-Ui). Auquel cas cette codebase devient obsolète. Mais on s'en recausera, je ferme ce ticket en attendant :smiley:.
